# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c81f8ca0d2bdafeca0433c0bd9c6a40c85b0f8fdb033586cf9b85fa6af8bc00250331aa12d1377c93675a206e9f2f57a1c6fad24f5b2b72f93c2cc6d18ffa30

test:
  secret_key_base: 99c71c483442a66a8169bfe0182425e9c9a3e13d051ec14db74a33023f2bbdabd71b0a9ba19c399d657c62ce733e84560a04f027b2117d3e5dcea3d09dd11d49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
